
version: '3'

networks:
  hlsn-network:
      name: hlsn-network

volumes:
  mysqldb_s_0_data:
  mysqldb_s_1_data:
  mysqldb_s_2_data:
  proxysql_data:

services:

  mysqldb_s_0: &mysqldb_s
    image: mysql:8
    container_name: mysqldb_s_0
    restart: unless-stopped
    hostname: mysql_s_0
    volumes:
      - mysqldb_s_0_data:/var/lib/mysql
    ports:
      - 3360:3306
    networks:
      - hlsn-network
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_network
      MYSQL_USER: otus
      MYSQL_PASSWORD: high_load
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mysqldb_s_1:
    <<: *mysqldb_s
    container_name: mysqldb_s_1
    hostname: mysql_s_1
    volumes:
      - mysqldb_s_1_data:/var/lib/mysql
    ports:
      - 3361:3306

  mysqldb_s_2:
    <<: *mysqldb_s
    container_name: mysqldb_s_2
    hostname: mysql_s_2
    volumes:
      - mysqldb_s_2_data:/var/lib/mysql
    ports:
      - 3362:3306

  proxy_sql:
    image: proxysql/proxysql:2.4.7
    restart: always
    hostname: proxy_sql
    volumes:
      - proxysql_data:/var/lib/proxysql
      - ./proxysql.cnf:/etc/proxysql.cnf
    networks:
      - hlsn-network
    ports:
      # Mysql Client Port
      - 6033:6033
      # Mysql Admin Port
      - 6032:6032

  redis:
    image: redis:6.2
    hostname: redis
    ports:
      - "6379:6379"
    #command: redis-server --save 20 1 --loglevel warning --requirepass high_load
    networks:
      - hlsn-network
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50

  high-load-social-network-backend:
    build:
      context: .
      dockerfile: dockerfile
    image: high-load-social-network-backend
    container_name: high-load-social-network-backend
    restart: always
    depends_on:
      - proxy_sql
      - redis
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hlsn-network
    environment:
      DB_URL: jdbc:mysql://proxy_sql:6033/social_network?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: otus
      DB_PASSWORD: high_load
      HTTP_SERVER_HOST: 0.0.0.0
      HTTP_SERVER_PORT: 8080
      CACHE_URI: redis://redis:6379
      POST_FEED_LENGTH: 1000