
version: '3'

networks:
  hlsn-network:
      name: hlsn-network

services:

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    hostname: mysql
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - hlsn-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_network
      MYSQL_USER: otus
      MYSQL_PASSWORD: high_load
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  high-load-social-network-backend:
    build:
      context: .
      dockerfile: dockerfile
    image: high-load-social-network-backend
    container_name: high-load-social-network-backend
    restart: always
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hlsn-network
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/social_network?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: otus
      DB_PASSWORD: high_load
      HTTP_SERVER_HOST: 0.0.0.0
      HTTP_SERVER_PORT: 8080